apiVersion: pipecd.dev/v1beta1
kind: LambdaFunction
spec:
  name: SimpleFunction
  role: arn:aws:iam::76xxxxxxx:role/lambda-role
  image: 537765733031.dkr.ecr.us-east-1.amazonaws.com/hiep-test-pipecd:v0
  memory: 512
  timeout: 30
  environments:
    FOO: bar
  tags:
    app: simple
