apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: test-azure-plugin
  plugins:
    azure:
      kind: function
      functionManifest:
        resourceGroupName: testpipecdrg
        functionName: testpipecdcs3
        armTemplate:
          deploymentName: armdeployfunc
          deploymentTemplateFile: func-window-consumption.json
          deploymentParameterFile: func-window-consumption.parameters.json
        packageUri: https://testpipecdsa.blob.core.windows.net/testti-deploy/cs1.zip